#server
server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8
    max-threads: 1000
    min-spare-threads: 100

#spring
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/bskdb?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
    cache: false
  aop:
    proxy-target-class: false
  task:
    execution:
      pool:
        core-size: 5
        max-size: 16
        queue-capacity: 100
        keep-alive: 30
        allow-core-thread-timeout: false
      thread-name-prefix: spring.async.task-

#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.bsk.dican.entity
  mapper-locations: classpath:/mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true

#lOG
logging:
  level:
    com.bsk.dican.dao: debug
    
#page

